import { User } from "../../domain/entities/user.entity";
import { Role } from "../../shared/constants/roleenum";
import { SignupDTO } from "../dto/auth/signup.dto";

export class UserMapper {
  static toDomainSignup(
    dto: SignupDTO,
    passwordHash: string,
    otp: string,
    otpExpiresAt: Date
  ): User {
    const now = new Date();

    return new User(
      "", // id will be generated by DB
      null, // companyId
      dto.name,
      dto.email,
      passwordHash,
      Role.COMPANY_ADMIN,
      null, // avatarUrl
      "PENDING_VERIFICATION",
      "LOCAL",
      otp,
      otpExpiresAt,
      null, // settings
      now,
      now,
      null // lastLoginAt
    );
  }
}