name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build backend
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devsync-PR-

            echo "📥 Pull latest code"
            git pull origin main

            echo "📦 Backend setup"
            cd backend
            npm install
            npm run build

            echo "♻️ Restart backend"
            pm2 restart backend || pm2 start dist/server.js --name backend

            echo "✅ Backend deployment finished"