name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [backend, frontend]

    steps:
      - uses: actions/checkout@v4

      # 🔧 Build frontend
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # 📦 ZIP frontend (IMPORTANT)
      - name: Zip frontend
        run: |
          cd frontend
          zip -r dist.zip dist

      # 🚀 FAST COPY (single file)
      - name: Copy zip to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "frontend/dist.zip"
          target: "/home/ubuntu/"
          timeout: 120s
          command_timeout: 10m

      # 🚀 DEPLOY
      - name: Deploy Backend + Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 120s
          command_timeout: 10m
          script: |
            echo "📦 Backend"
            cd ~/devsync-PR-/backend
            git pull
            npm install
            npm run build
            pm2 restart backend

            echo "📦 Frontend unzip"
            cd /home/ubuntu
            unzip -o dist.zip

            echo "🚀 Deploy frontend"
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            sudo systemctl restart nginx